//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int application_id { get; set; }
        public int company { get; set; }
        public string job_title { get; set; }
        public int discovery { get; set; }
        public int contact_method { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Contact Contact { get; set; }
    }
}
