//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discover
    {
        public int discover_id { get; set; }
        public string discovery { get; set; }
    }
}
